import { Router } from "express";
import locationAppRoute from "@/modules/location/routes/app/v1/index";
import { authRouter, userRouter } from "@/modules/user/routes/app/v1";
import parkingSubscriptionFeeAppRoute from "@/src/modules/parkingSubscriptionFee/routes/app/v1/subscriptionFeeAppRoute";
import vehicleAppRoute from "@/modules/parkingSubscriptionFee/routes/app/v1/vehicleAppRoute";
import parkingSlotAppRoute from "@/modules/parkingArea/routes/app/v1/parkingSlotAppRoute";
import parkingAreaAppRoute from "@/modules/parkingArea/routes/app/v1/parkingAreaAppRoute";
import subscriptionPaymentAppRoute from "../modules/parkingSubscriptionFee/routes/app/v1/subscriptionPaymentAppRoute";
import reservationAppRouter from "../modules/reservation/routes/app/v1/reservation.app.router";
import reservationPaymentAppRouter from "../modules/reservation/routes/app/v1/reservationPayment.app.router";
import roleRouter from "@/modules/user/routes/app/v1/role.route";
import ratingAppRouter from "@/modules/parkingArea/routes/app/v1/rating.app.router";
const appRouter: Router = Router();
 appRouter.use('/v1/user', userRouter);
 appRouter.use('/v1/role', roleRouter);
 appRouter.use('/v1/auth', authRouter);
appRouter.use("/v1/province",locationAppRoute.provinceAppRouter);
appRouter.use("/v1/district",locationAppRoute.districtAppRouter);
appRouter.use("/v1/city",locationAppRoute.cityAppRouter);
appRouter.use("/v1/parking-subscription-fee",parkingSubscriptionFeeAppRoute);
appRouter.use("/v1/vehicle",vehicleAppRoute);
appRouter.use("/v1/parking-area",parkingAreaAppRoute);
appRouter.use("/v1/parking-slot",parkingSlotAppRoute);
appRouter.use("/v1/subscription-payment",subscriptionPaymentAppRoute);
appRouter.use("/v1/reservation",reservationAppRouter);
appRouter.use("/v1/reservation-payment",reservationPaymentAppRouter);
appRouter.use("/v1/rating",ratingAppRouter);

export default appRouter;
